name: lootify
on:
  workflow_dispatch
  # schedule:
  #   - chron: 0 7 5 * *
    
jobs:
  lootify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        
      - name: pip install
        run: pip install -r requirements.txt

      - name: lootify gainsborough
        run: |
          export user=${{ secrets.GAINSBOROUGH }} pass=${{ secrets.PASSWORD }}
          python3 lootify.py





